/////////////////////////
//  PROJECT EULER 0002
//  diegogerwig
////////////////////////

/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main (void)
{
    int x= 1, y= 2, z;
    int sum_even = 2;

    while (z < 4000000)
    {
        z = x +y;
        printf("%i\n", sum_even);
        if(z%2 == 0)
            sum_even += z;
        x = y;
        y = z;
    }
    return (0);
}
