"""
Project Euler Problem 44: Pentagon Numbers

Pentagonal numbers are generated by Pn = n(3n-1)/2.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference 
are pentagonal and D = |Pk - Pj| is minimised.

What is the value of D?
"""

import math

def is_pentagonal(x):
    """
    Checks if x is a pentagonal number using the inverse formula:
    n = (1 + sqrt(1 + 24*x)) / 6
    """
    if x <= 0: return False
    
    # We calculate the discriminant part
    val = 1 + 24 * x
    sqrt_val = math.isqrt(val)
    
    # Check if perfect square AND satisfies the divisibility condition
    if sqrt_val * sqrt_val == val:
        return (1 + sqrt_val) % 6 == 0
        
    return False

def solve_pentagon_numbers():
    # List to cache generated pentagonal numbers for fast access
    # Though we iterate k upwards, we need fast access to P_j values.
    pentagonals = []
    
    k = 1
    found = False
    
    while not found:
        # Generate P_k
        pk = k * (3 * k - 1) // 2
        pentagonals.append(pk)
        
        # Check against all previous P_j (iterating backwards is key for minimality)
        # pentagonals list has indices 0 to k-1. We iterate j from k-1 down to 0.
        for j in range(k-1, -1, -1):
            pj = pentagonals[j]
            
            diff = pk - pj
            
            # 1. Check if Difference is Pentagonal
            # If diff is not pentagonal, no need to check sum.
            if is_pentagonal(diff):
                
                sum_val = pk + pj
                
                # 2. Check if Sum is Pentagonal
                if is_pentagonal(sum_val):
                    print(f"Found Pair!")
                    print(f"P_k = {pk} (k={k+1})") # +1 because list is 0-indexed, math is 1-indexed
                    print(f"P_j = {pj} (j={j+1})")
                    print(f"Sum = {sum_val}")
                    print(f"Difference (D) = {diff}")
                    found = True
                    break
        k += 1

if __name__ == "__main__":
    solve_pentagon_numbers()