"""
Project Euler Problem 45: Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle    Tn = n(n+1)/2
Pentagonal  Pn = n(3n-1)/2
Hexagonal   Hn = n(2n-1)

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Key Insight: Every Hexagonal number is also a Triangular number.
We only need to find a Hexagonal number that is also Pentagonal.
"""

import math

def is_pentagonal(num):
    """
    Inverse Pentagonal check:
    If Pn = n(3n-1)/2, then 3n^2 - n - 2Pn = 0.
    Using quadratic formula, n = (1 + sqrt(1 + 24*Pn)) / 6
    """
    discriminant = 1 + 24 * num
    
    # Check if discriminant is perfect square
    root = math.isqrt(discriminant)
    
    if root * root != discriminant:
        return False
        
    # Check if (1 + root) is divisible by 6
    return (1 + root) % 6 == 0

def solve_tri_pen_hex():
    # Start from the next index after the example given (H_143)
    n = 144
    
    while True:
        # Generate Hexagonal number
        hex_num = n * (2 * n - 1)
        
        # Check if it is Pentagonal (it is automatically Triangular)
        if is_pentagonal(hex_num):
            print(f"Match found at Hexagonal index {n}")
            print(f"The number is: {hex_num}")
            break
            
        n += 1

if __name__ == "__main__":
    solve_tri_pen_hex()