"""
Project Euler Problem 29: Distinct Powers

Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
If they are then placed in numerical order, with any repeats removed, we get a sequence of distinct terms.

How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
"""

def solve_distinct_powers():
    # 1. Initialize a set to store the powers.
    # Sets in Python are unordered collections of unique elements.
    distinct_terms = set()
    
    # 2. Define limits (inclusive)
    min_val = 2
    max_val = 100
    
    # 3. Double Loop (Brute Force)
    # We calculate every possible combination of a^b
    # 99 * 99 = 9801 calculations, which is trivial for a modern CPU.
    for a in range(min_val, max_val + 1):
        for b in range(min_val, max_val + 1):
            
            # Calculate power
            power = a ** b
            
            # Add to set (duplicates are automatically ignored)
            distinct_terms.add(power)
            
    # 4. Result
    count = len(distinct_terms)
    
    print(f"Range: {min_val} <= a, b <= {max_val}")
    print(f"Total distinct terms found: {count}")

if __name__ == "__main__":
    solve_distinct_powers()